config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources 'lists', only: [:index, :new , :show, :create] do
    resources 'bookmarks', only: [:new]
  end

  resource 'bookmarks', only: [:create]
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: "bookmark"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :blank_form

  def blank_form
    @list_new = List.new
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    bookmark = Bookmark.new(bookmark_params)
    if bookmark.save
      redirect_to list_path(bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    list = bookmark.list
    bookmark.destroy
    redirect_to list_path(list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.where(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    list = List.create(list_params)
    redirect_to list_path(list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add Bookmark</h1>

<%= simple_form_for @bookmark do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.hidden_field :list_id, value: @list.id %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <%= link_to "ScuffedLists", lists_path, class:"navbar-brand" %>
        <div class="form_flex">
          <%= simple_form_for @list_new do |f| %>
            <%= f.input :name, label: false, placeholder: "List Name" %>
            <%= f.input :photo, as: :file, label: false %>
            <%= f.submit "Create List", class: "btn btn-outline-success"%>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container text-center">
  <ul class="list-group list-group-numbered">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <li class="list-group-item btn btn-primary mt-3"><%= list.name %></li>
      <% end %>
    <% end %>
  </ul>

  <%= link_to "New", new_list_path, class: "btn btn-success mt-3"%>
</div>

app/views/lists/new.html.erb
<div class="container text-center">
  <h1>Create List</h1>

  <%= simple_form_for @list_new do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file, label: false %>
    <%= f.submit "Create List" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="list-header text-center text-white" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <h1><%= @list.name %></h1>
</div>
<div class="container text-center">
  <ol class="d-flex flex-wrap justify-content-around">
    <% @bookmarks.each do |bm| %>
      <li class="card shadowed m-3" style="width: 18rem">
        <%= image_tag bm.movie.poster_url, class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= bm.movie.title %></h5>
          <p class="card-text"><%= bm.comment %></p>
          <%= link_to "Delete", bookmark_path(bm), data: { turbo_method: :delete, turbo_confirm: "Delete bookmark?" }, class: "btn btn-danger" %>
        </div>
      </li>
    <% end %>
  </ol>

  <%= link_to "Add film", new_list_bookmark_path(@list), class: "btn btn-primary"%>
</div>